# Generated by Django 5.1.3 on 2024-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_languages_bookinstance_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='', help_text='Enter the contents of the book', max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(default='', help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
